<?php

namespace Showcase\Action\Demo;
use ObjectivePHP\Application\Action\AbstractAction;
use ObjectivePHP\Application\ApplicationInterface;
use Zend\Diactoros\Response\JsonResponse;

/**
 * Created by PhpStorm.
 * User: gauthier
 * Date: 11/12/2015
 * Time: 23:52
 */
class Json extends AbstractAction
{
    function run(ApplicationInterface $app)
    {
        return new JsonResponse(['this has been automatically generated by returning a ' . JsonResponse::class . ' instance from ' . __CLASS__]);
    }

}