<?php

namespace Showcase\Action\Demo;

use ObjectivePHP\Application\Action\AjaxAction;
use ObjectivePHP\Application\Action\HttpAction;
use ObjectivePHP\Application\ApplicationInterface;
use Zend\Diactoros\Response\JsonResponse;

/**
 * Created by PhpStorm.
 * User: gauthier
 * Date: 11/12/2015
 * Time: 23:52
 */
class Json extends AjaxAction
{

    function run(ApplicationInterface $app)
    {
        return ['this has been automatically generated by returning a ' . JsonResponse::class . ' instance from ' . __CLASS__];
    }

}