<?php
    // change layout
    use ObjectivePHP\Html\Tag\Tag;

    $config->layouts->layout = 'home';
?>


<?php

    /*
     * Tag helper calls below will produce this html code:
     *
     * <div class="page-header">
     *      <h1>What will you find here?</h1>
     *  </div>
     */

    echo Tag::div(Tag::h1('What will you find here?'), 'page-header');

?>

<p>
    This project provides developers with demos of the Objective PHP framework and components.
</p>
<p>
    To access the demos, use the <?= Tag::i('Demos') ?> menu entry on top of this page.
</p>
