<?php
use ObjectivePHP\Application\View\Helper\Vars;
    use ObjectivePHP\Application\Workflow\WorkflowInterface;

?>

Below is the tree of default ObjectivePHP/Application workflow events.
<br /><br />
<?php

$workflow =  Vars::get('workflow');
?>

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Workflow steps</div>
        <div class="panel-body">
            <p>
                The steps below are the actual steps of the current workflow. This is a fully dynamic table, generated
                from the actual workflow running the page.
            </p>
        </div>

        <!-- Table -->
        <table class="table">
            <thead>
                <th>Step</th>
                <th>Event</th>
                <th>Description</th>
            </thead>
            <tbody>
            <?php
                $index = 1;
                display_workflow($workflow, $workflow->getName(), $index);
            ?>
            </tbody>
    </table>
</div>

<?php


    /**
     * @param $workflow
     */
    function display_workflow($workflow, $prefix, &$index)
    {
        if($workflow->doesAutoTriggerPrePostEvents())
        {
            display_event($index++, implode('.', [$prefix, 'pre']), 'Auto-triggered "pre" event');
        }

        foreach($workflow->getSteps() as $step)
        {
            if ($step instanceof WorkflowInterface)
            {
                display_workflow($step, $prefix . '.' . $step->getName(), $index);
            }
            else
            {
                display_event($index++, implode('.', [$prefix, $step->getName()]), $step->getDescription());
            }
        }
        if($workflow->doesAutoTriggerPrePostEvents())
        {
            display_event($index++, implode('.', [$prefix, 'post']), 'Auto-triggered "post" event');
        }
    }

    function display_event($index, $event, $description)
    {
        echo '<tr>';
        echo '<td>' . $index . '</td>';
        echo '<td><a href="?' . $event . '">' . $event . '</a></td>';
        echo '<td>' . $description . '</td>';
        echo '</tr>';
    }


