<?php
    use ObjectivePHP\Application\Config\ApplicationName;
?>
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
            <a class="navbar-brand" href="/"><?= $this->getApplication()->getConfig()->get(ApplicationName::class) ?></a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="http://objective-php.rtfd.org" target="_blank">Documentation</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Demos <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Output</li>
                        <li><a href="/demo/html/html-tag">Html</a></li>
                        <li><a href="/demo/json">Json</a></li>
                        <li class="dropdown-header">Events</li>
                        <li><a href="/demo/events/workflow">Workflow</a></li>
                        <li><a href="/demo/events/load">Higher load</a></li>
                        <li class="dropdown-header">Services</li>
                        <li><a href="/demo/services/definitions">Definitions</a></li>
                        <li class="dropdown-header">Doctrine</li>
                        <li><a href="/demo/doctrine/listing">Listing</a></li>
                        <li><a href="/demo/doctrine/entity-parameter?<?= rand(1001, 30000) ?>">Entity Parameter</a></li>
                        <!-- <li class="dropdown-header">Eloquent</li> -->
                        <!-- <li><a href="/demo/eloquent/listing">Listing</a></li> -->
                        <!--- <li><a href="/demo/eloquent/entity-parameter?<?= rand(1001, 30000) ?>">Entity Parameter</a></li> -->
                    </ul>
                </li>
                <!--
                <li><a href="/about">About</a></li>
                <li><a href="/contact">Contact</a></li>
                -->
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
