<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><?= $config->app->name ?></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Demos <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Events</li>
                        <li><a href="/demo/events/workflow">Workflow</a></li>
                        <li><a href="/demo/events/load">Higher load</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">Services</li>
                        <li><a href="/demo/services/definitions">Definition</a></li>
                    </ul>
                </li>
                <!--
                <li><a href="/about">About</a></li>
                <li><a href="/contact">Contact</a></li>
                -->
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>