
<?php
    use ObjectivePHP\Application\View\Helper\Vars;

    Vars::set('page.subtitle', 'Triggers plenty of random triggers with loads of callbacks');
?>


    <h3>Current configuration:</h3>

    <h3>
        <span class="label label-primary">
            <span class="badge"><?= Vars::get('events.triggered') ?></span> Triggers
        </span>
    </h3>
    <h3>
        <span class="label label-danger">
            <span class="badge"><?= Vars::get('callbacks.bound') ?></span> Bound callbacks
        </span>
    </h3>
    <h3>
        <span class="label label-warning">
            <span class="badge"><?= Vars::get('callbacks.ran') ?></span> Ran callbacks
        </span>
    </h3>

    <h3>
        <span class="label label-success">
            Total time <span class="badge"><?= Vars::get('time.elapsed') ?></span> ms
        </span>
    </h3>

<br />
<br />
<br />
<p>
    You can play with parameters "callbacks" ans "triggers" to change the number of events triggered and/or callbacks connected.
    <br />
    <br />
    <a href="?callbacks=500&triggers=100">Example with 500 callbacks and 100 triggers</a> Don't be afraid to click this link, it should not last that long :)

</p>
