<?php
    use ObjectivePHP\Application\View\Helper\Vars;
    use ObjectivePHP\Html\Tag\Tag;
    use ObjectivePHP\Primitives\Collection\Collection;

?>

Below is the tree of default ObjectivePHP/Application workflow events.
<br/><br/>
<?php
    $workflow = Vars::collection('workflow');

?>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><?= Vars::get('page.title') ?></div>
    <div class="panel-body">
        <p>
            The steps below are the actual steps of the current workflow. This is a fully dynamic table, generated
            from the actual workflow running the page.
        </p>
    </div>

    <!-- Table -->
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Hook</th>
            <th>MiddleWare</th>
        </tr>
        </thead>
        <tbody>
        <?php

            $workflow->each(function ($middleWares, $hook)
            {
                Tag::tr(Tag::td(Tag::strong($hook))->addAttribute('colspan', 2));


                if (!$middleWares)
                {
                    $middleWares[] = 'No Hook has been plugged here';
                }

                Collection::cast($middleWares)->each(function ($middleWare)
                {
                    Tag::tr([Tag::td(), Tag::td($middleWare)]);

                })
                ;

            });


        ?>
        </tbody>
    </table>
</div>

