<?php

    use Doctrine\Common\Util\Debug;
    use ObjectivePHP\Application\View\Helper\Currency;
    use ObjectivePHP\Application\View\Helper\Date;
    use ObjectivePHP\Application\View\Helper\Vars;
    use ObjectivePHP\Html\Tag\Tag;
    use ObjectivePHP\Primitives\Collection\Collection;

    Vars::set('page.title', 'Doctrine Parameter');
    Vars::set('page.subtitle', 'Restores an entity from a query parameter');

    $employee = Vars::get('employee');


    echo Tag::small(Tag::a('back to employee list')->addAttribute('href', '/demo/doctrine/listing'));
    echo Tag::h2($employee['first_name'] . ' ' . $employee['last_name']);

    echo
     Tag::dt('Gender') .
     Tag::dd($employee['gender'] == 'M' ? 'Male' : 'Female') .
     Tag::dt('Birth Date') .
     Tag::dd($employee['birth_date']->format('d/m/Y')) .
     Tag::dt('Hire Date') .


     Tag::dd($employee['hire_date']->format('d/m/Y'));

    if(count($employee['titles']))
    {
        echo Tag::h2('Titles');
        echo Tag::ul();
        foreach($employee['titles'] as $title)
        {
            $output = 'From ' . Date::format($title['from']);
            if ($title['to']) $output .= ' to ' . Date::format($title['to']);
            $output .= ': ' . $title['title'];
            echo Tag::li($output);

        };
        echo Tag::ul()->close();
    }

    if(count($employee['salaries']))
    {
        echo Tag::h2('Salaries');
        echo Tag::ul();
        foreach($employee['salaries'] as $salary)
        {
            $output = 'From ' . Date::format($salary['from']);
            if ($salary['to']) $output .= ' to ' . Date::format($salary['to']);
            $output .= ': ' . Currency::format($salary['amount']);
            echo Tag::li($output);
        };
        echo Tag::ul()->close();
    }

