<?php

    use Doctrine\Common\Util\Debug;
    use ObjectivePHP\Application\View\Helper\Currency;
    use ObjectivePHP\Application\View\Helper\Date;
    use ObjectivePHP\Application\View\Helper\Vars;
    use ObjectivePHP\Html\Tag\Tag;
    use ObjectivePHP\Primitives\Collection\Collection;

    Vars::set('page.title', 'Doctrine simple demo');
    Vars::set('page.subtitle', 'Using MySQL employees sample database');

    Vars::collection('employees')->each(function($employee)
    {
        echo Tag::h2(Tag::a($employee['first_name'] . ' ' . $employee['last_name'])->addAttribute('href', '/demo/doctrine/parameter?' . $employee['employee_no']));

        echo
         Tag::dt('Gender') .
         Tag::dd($employee['gender'] == 'M' ? 'Male' : 'Female') .
         Tag::dt('Birth Date') .
         Tag::dd($employee['birth_date']->format('d/m/Y')) .
         Tag::dt('Hire Date') .


         Tag::dd($employee['hire_date']->format('d/m/Y'));


        echo Tag::hr();

    });