<?php
    use ObjectivePHP\Application\View\Helper\Vars;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?= $config->app->name ?></title>

    <!-- Bootstrap core CSS -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/theme.css" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body role="document">

<?php include __DIR__ . '/partials/navbar.phtml'; ?>

<div class="container theme-showcase" role="main">

    <div class="page-header">
        <h1>
            <?= Vars::get('page.title') ?>
            <?= Vars::string('page.subtitle')->prepend('<small>')->append('</small>') ?>
        </h1>
    </div>

    <div class="bs-example panel" id="source-buttons">
        <p>
            <a class="btn btn-primary" href="#action-source" data-parent="#source-viewers">
                Show Action
            </a>

            <a class="btn btn-primary" href="#view-source" data-parent="#source-viewers">
                Show View
            </a>
        </p>
        <div id="source-viewers">

            <div class="source-viewer collapse" id="action-source">
                <div class="well">
                    :action-source
                </div>
            </div>
            <div class="source-viewer collapse" id="view-source">
                <div class="well">
                    :view-source
                </div>
            </div>
        </div>
    </div>
    <div>
        <?= $content  ?>
    </div>
</div>
<!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function () {
        $('#source-buttons  a').each(function (index, button) {
            $(button).on('click', function(event){
                target = $(event.currentTarget.hash);
                $($(event.currentTarget).data('parent')).find('.source-viewer').not('#' + target.attr('id')).hide();
                target.toggle();
                return false;
            });
        });
    });
</script>
</body>
</html>

